services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - /Users/hyewon/cert/ZscalerRootCertificate-2048-SHA256.crt:/usr/local/share/ca-certificates/zscaler.crt
    environment:
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler.crt
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - API_INTERNAL_URL=http://backend:8000
    depends_on:
      - backend
